### PR TITLE
Silence Logging by default

### PR DESCRIPTION
**Pull request by jmarsh24**
By default this library sets the silence_logging config to false which causes the developer logs to be polluted by default. (a single sql query for every request). I propose that that this should be an opt in mode. This PR changes the default.

here is an example of what the developer sees upon initial installation.

```sh
web    |   SolidQueue::ScheduledExecution Pluck (5.3ms)  SELECT "solid_queue_scheduled_executions"."job_id" FROM "solid_queue_scheduled_executions" WHERE "solid_queue_scheduled_executions"."scheduled_at" <= $1 ORDER BY "solid_queue_scheduled_executions"."scheduled_at" ASC, "solid_queue_scheduled_executions"."priority" ASC LIMIT $2 FOR UPDATE SKIP LOCKED  [["scheduled_at", "2024-02-06 13:48:23.493518"], ["LIMIT", 500]]
web    |   TRANSACTION (0.6ms)  COMMIT
web    |   SolidQueue::Pause Pluck (1.9ms)  SELECT "solid_queue_pauses"."queue_name" FROM "solid_queue_pauses"
web    |   TRANSACTION (0.9ms)  BEGIN
web    |   SolidQueue::ReadyExecution Pluck (2.9ms)  SELECT "solid_queue_ready_executions"."job_id" FROM "solid_queue_ready_executions" ORDER BY "solid_queue_ready_executions"."priority" ASC, "solid_queue_ready_executions"."job_id" ASC LIMIT $1 FOR UPDATE SKIP LOCKED  [["LIMIT", 5]]
web    |   TRANSACTION (1.4ms)  COMMIT
web    |   SolidQueue::Pause Pluck (1.8ms)  SELECT "solid_queue_pauses"."queue_name" FROM "solid_queue_pauses"
web    |   TRANSACTION (1.2ms)  BEGIN
web    |   SolidQueue::ReadyExecution Pluck (5.9ms)  SELECT "solid_queue_ready_executions"."job_id" FROM "solid_queue_ready_executions" ORDER BY "solid_queue_ready_executions"."priority" ASC, "solid_queue_ready_executions"."job_id" ASC LIMIT $1 FOR UPDATE SKIP LOCKED  [["LIMIT", 5]]
web    |   TRANSACTION (0.6ms)  COMMIT
web    |   SolidQueue::Pause Pluck (1.5ms)  SELECT "solid_queue_pauses"."queue_name" FROM "solid_queue_pauses"
web    |   TRANSACTION (0.4ms)  BEGIN
web    |   SolidQueue::ReadyExecution Pluck (2.1ms)  SELECT "solid_queue_ready_executions"."job_id" FROM "solid_queue_ready_executions" ORDER BY "solid_queue_ready_executions"."priority" ASC, "solid_queue_ready_executions"."job_id" ASC LIMIT $1 FOR UPDATE SKIP LOCKED  [["LIMIT", 5]]
web    |   TRANSACTION (0.6ms)  COMMIT
web    |   SolidQueue::Pause Pluck (0.8ms)  SELECT "solid_queue_pauses"."queue_name" FROM "solid_queue_pauses"
web    |   TRANSACTION (0.3ms)  BEGIN
web    |   SolidQueue::ReadyExecution Pluck (1.7ms)  SELECT "solid_queue_ready_executions"."job_id" FROM "solid_queue_ready_executions" ORDER BY "solid_queue_ready_executions"."priority" ASC, "solid_queue_ready_executions"."job_id" ASC LIMIT $1 FOR UPDATE SKIP LOCKED  [["LIMIT", 5]]
web    |   TRANSACTION (0.3ms)  COMMIT
web    |   SolidQueue::Pause Pluck (3.2ms)  SELECT "solid_queue_pauses"."queue_name" FROM "solid_queue_pauses"
web    |   TRANSACTION (0.7ms)  BEGIN
web    |   SolidQueue::ReadyExecution Pluck (2.2ms)  SELECT "solid_queue_ready_executions"."job_id" FROM "solid_queue_ready_executions" ORDER BY "solid_queue_ready_executions"."priority" ASC, "solid_queue_ready_executions"."job_id" ASC LIMIT $1 FOR UPDATE SKIP LOCKED  [["LIMIT", 5]]
web    |   TRANSACTION (0.7ms)  COMMIT
web    |   SolidQueue::Pause Pluck (2.0ms)  SELECT "solid_queue_pauses"."queue_name" FROM "solid_queue_pauses"
web    |   TRANSACTION (0.6ms)  BEGIN
web    |   SolidQueue::ReadyExecution Pluck (2.2ms)  SELECT "solid_queue_ready_executions"."job_id" FROM "solid_queue_ready_executions" ORDER BY "solid_queue_ready_executions"."priority" ASC, "solid_queue_ready_executions"."job_id" ASC LIMIT $1 FOR UPDATE SKIP LOCKED  [["LIMIT", 5]]
web    |   TRANSACTION (0.5ms)  COMMIT
web    |   SolidQueue::Pause Pluck (0.9ms)  SELECT "solid_queue_pauses"."queue_name" FROM "solid_queue_pauses"
web    |   TRANSACTION (0.4ms)  BEGIN
web    |   SolidQueue::ReadyExecution Pluck (2.0ms)  SELECT "solid_queue_ready_executions"."job_id" FROM "solid_queue_ready_executions" ORDER BY "solid_queue_ready_executions"."priority" ASC, "solid_queue_ready_executions"."job_id" ASC LIMIT $1 FOR UPDATE SKIP LOCKED  [["LIMIT", 5]]
web    |   TRANSACTION (0.4ms)  COMMIT
web    |   SolidQueue::Pause Pluck (1.8ms)  SELECT "solid_queue_pauses"."queue_name" FROM "solid_queue_pauses"
web    |   TRANSACTION (0.6ms)  BEGIN
web    |   SolidQueue::ReadyExecution Pluck (2.1ms)  SELECT "solid_queue_ready_executions"."job_id" FROM "solid_queue_ready_executions" ORDER BY "solid_queue_ready_executions"."priority" ASC, "solid_queue_ready_executions"."job_id" ASC LIMIT $1 FOR UPDATE SKIP LOCKED  [["LIMIT", 5]]
```

### CODE REVIEW

**Comment by jmarsh24** [comment]
@rosa Why do the tests fail here if I have no touched the gemfile?

**Comment by rosa** [comment]
> @rosa Why do the tests fail here if I have no touched the gemfile?

Because of an unrelated problem, already fixed in ef42e6ade8b1f6c73214e74de58e74a1130715b5, so no worries about it.

**Review by rosa — CHANGES_REQUESTED** [review]
Thanks! Could you update also the `README`, the part about `silence_polling` option? 
It's also possible

**Comment by jmarsh24** [comment]
@rosa I have updated the read me 😄

**Pull request merged**
